# Generated by Django 4.2.4 on 2025-10-23 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('rko', 'Расчетно-кассовое обслуживание'), ('salary', 'Зарплатный проект'), ('acquiring', 'Торговый эквайринг')], max_length=100, verbose_name='Тип услуги')),
                ('description', models.TextField(verbose_name='Описание')),
                ('icon', models.ImageField(upload_to='service_icons/', verbose_name='Иконка услуги')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=50, unique=True, verbose_name='Номер договора')),
                ('client_name', models.CharField(max_length=255, verbose_name='Клиент')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmstu_lab.bankservice', verbose_name='Услуга')),
            ],
        ),
    ]
